### ISSUE TITLE
RFC: Move filefinder to liblcf

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/liblcf#137]
Having a filefinder when only working with liblcf would be quite useful sometimes.
For LCF2XML I added my own case-insensitive RPG_RT.ini search but for more complex programs targeting liblcf file finding is probably needed...
Your opinion?

There are 2 boost dependencies:

``` cpp
#include <boost/container/flat_map.hpp>
#include <boost/optional.hpp>
```

Flat-map could be replaced with std::map and boost::optional with maybe... empty string?

Another issue is the reference of Main_Data::project_path and Utils::ToWideString.

RTP stuff could be kept in the Player, is not generally useful.

**Comment by fdelapena** [comment]
Looks good to me, however there will need to pass some output logging level from liblcf to player (debug, warning, error) from filefinder messages.

Will this feature move encoding detection into liblcf too?

**Comment by fdelapena** [comment]
> RTP stuff could be kept in the Player, not generally useful.

I think it could be useful for Editor-Qt project import, specially the RTP table replacement.

Also, moving map tile reading logic would benefit dupe code in Editor-Qt and reusable in other potential tools like map rendering or exporting to pictures, but I think this is out of the scope of this RFC.

**Comment by Ghabry** [comment]
@carstene1ns proposed the first LCF Tool that needs filefinding but not LCF parsing (gencache).
In the long term I see the FileFinder as an abstraction layer over any type of directories/files, e.g. in zip archives. Like a more modern version of PhysFS ;)

Potential candidates we already have are:
Directory access: opendir vs. FindFirstFile vs. standalone mode in Android (Reading APK)
File access: fopen vs. _wfopen vs. sdmc_open vs. ZIP/APK access

So maybe it makes sense to not merge the filefinder into liblcf (except stuff that will be only useful in combination with liblcf, like the RTP table) and create another library instead 😱

**Comment by Ghabry** [comment]
Based on current development I don't think that a filefinder is needed anymore in liblcf.

The editor also got a file finder now but it is not comparable to the player filefinder at all.

Only has case insensitive search in a folder via Qt and multi extension search. Is very compact code.
Imo complecated RTP lookup isn't needed for it.

All the complexity for caching, platform dependent optimization etc is not needed here.

The tools could use std:: filesystem but this is c++17.

**Comment by fdelapena** [comment]
Having own implementation in Editor and if we can use c++17 in tools if needed (not a critical component to be portable on exotic platforms), I'm in favor to close this RFC.

**Comment by Ghabry** [comment]
imo this isn't really needed anymore, lcf consumes normal i/ostreams and the requirements are too different depending on the app.
