### ISSUE TITLE
Homebrew formula test

### ISSUE THREAD

**Issue by tomyun** [EasyRPG/liblcf#147]
I've just made a Homebrew formula for `libclf` and pull request to Homebrew/homebrew-games#299. It's tested on my local machine to build EasyRPG Player and looked fine.

If you could take a look and give any comment or suggestion, it'd be really helpful. Especially, it currently lacks a test case for the formula. Formulae for development libraries are usually equipped with a snippet that compiles a source code to see if the library really works. I wonder if there's any short sample code/data to test `liblcf` in a nice way.

**Comment by Ghabry** [comment]
A simple test case that uses many parts of liblcf is to convert a binary file to XML and back. And afterwards diff the files (sha1sum) if they are the same (Map0001.lmu and the generated Map0002.lmu).
You can get Map0001 from our test game:
https://github.com/EasyRPG/TestGame/blob/master/TestGame-2000/Map0001.lmu

Don't have a suitable build env here so not sure if the following code compiles but should be almost correct ;)

```
// Converts Map0001.lmu to XML and then back to Map0002.lmu

#include <cstring>
#include <iostream>
#include <string>

#include "lmt_reader.h"
#include "reader_util.h"

int main(int argc, char** argv)
{
	// Load LMU map file
	std::auto_ptr<RPG::Map> file = LMU_Reader::Load("Map0001.lmu", "1252");
	if (file.get() == NULL) {
		std::cerr << "LMU load error: " << LcfReader::GetError() << std::endl;
		return 1;
	}

	// Save to XML
	if (!LMU_Reader::SaveXml("Map0001.xml", *file)) {
		std::cerr << "LMU save XML error: " << LcfReader::GetError() << std::endl;
		return 1;
	}

	// Load saved XML
	file = LMU_Reader::LoadXml("Map0001.xml");
	if (file.get() == NULL) {
		std::cerr << "LMU XML load error: " << LcfReader::GetError() << std::endl;
		return 1;
	}
	
	// Convert back to LMU
	if (!LMU_Reader::Save("Map0002.lmu", *file, "1252"), "LMU save") {
		std::cerr << "LMU save error: " << LcfReader::GetError() << std::endl;
		return 1;
	}
	
	return 0;
}
```

**Comment by Zegeri** [comment]
Ghabry, this wouldn't work for now. There are some subtle differences in how RPG_RT and liblcf write these files. For example empty arrays will appear in files generated by RPG_RT as:
```
XX     01    00
^Index ^Size ^Content
```
While liblcf would write it as:
```
XX     00
^Index ^Size
```
Both are interpreted by RPG_RT and liblcf the same way, but the binary diff will differ.

**Comment by Ghabry** [comment]
ugh, you are right. Will work on a different test case.

**Comment by Zegeri** [comment]
How about doing:
lcf2xml Map0001.lmu A.emu
lcf2xml A.emu temp.lmu
lcf2xml temp.lmu B.emu
diff A.emu B.emu (and check the exit code)

That might catch some errors and it should never give false positives.

**Comment by Ghabry** [comment]
Right. Just convert to XML files twice and diff them.

@tomyun
Is it fine when a test case depends on another external tool that must be compiled beforehand (lcf2xml) or do you want some source that does the steps that Zegeri suggested.
Both would be the same complexity to set up (because lcf2xml only consists of one cpp file).

**Comment by fdelapena** [comment]
There is also a [time stamp test](https://github.com/EasyRPG/liblcf/blob/master/Makefile.am#L256), which checks if the file format time stamp is being read properly. It can be run with `make check`. The time stamp test is pretty weak and a XML -> LCF -> XML test looks definitely better and more focused. Attaching some small file to the formula, e.g. a simple one map RPG_RT.lmt or a 20x15 MapXXXX.lmu converted to XML looks nice.

**Comment by tomyun** [comment]
A test case that runs with actual LCF files would be better, but `test` block in Homebrew formula seems not likely for full fledged tests. Most of the test cases do not depends on additional tools nor external files. I think a simple timestamp check function would be enough to see if we got the library built correctly.

Now the formula is updated and waiting for CI build. Thanks for your help!

**Comment by Ghabry** [comment]
Yeah if you don't want to rely on any external files then the timestamp code is probably your best option.

**Comment by fdelapena** [comment]
`brew install homebrew/games/easyrpg-player` is working now. Thank you @tomyun!
