### ISSUE TITLE
SaveMapEvent pending has unknown data type

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/liblcf#174]
The current assumption is BOOL but we got send a Ib savegame (created with RPG_RT, we don't write this field) that has a size of 4 and value 257. So this is not a compressed integer. Possible are Vector<Uint8> or Int (but if the field can be < 4 this will fail again).

[Save01.zip](https://github.com/EasyRPG/liblcf/files/174770/Save01.zip)

**Comment by Ghabry** [comment]
@CherryDT while you are around ;)

Can you tell us the purpose and format of chunk 0x67 for saved map events? 
Our guess was "This event will run after the current running event stops running." but we had a bool-flag for it and then got a save sent that had a non-bool value in this chunk.

**Comment by CherryDT** [comment]
That's whether the event was started by action button. It's what's used for the corresponding conditional branch option.

(Btw it's so weird you guys use hex for these chunks... They are actually decimal and have a numbering scheme...)

**Comment by CherryDT** [comment]
@Ghabry I know this doesn't belong here but GitHub has no private messaging anymore... Is your g...k@web.de email still active?

**Comment by Ghabry** [comment]
Yes it is still active.
My new address is gabriel at this domain: https://mastergk.de/

**Comment by Ghabry** [comment]
>That's whether the event was started by action button. It's what's used for the corresponding conditional branch option.

Really? We use 0x0D in SaveEventCommands for this

**Comment by CherryDT** [comment]
That's also correct. They are stored in both the event and the corresponding scripter class, hence why they exist twice in the save file too.

**Comment by Ghabry** [comment]
interesting >.> and that the value was 257 in one savegame, sounds not very bool-ish :D

**Comment by Ghabry** [comment]
The chunk has a proper name now and the parser can handle corrupt chunks well and there is no way for us to support data encoded in higher bytes for RPG_RT patches. Therefore I consider this as fixed.
