### ISSUE TITLE
Missing ID field in Map XML Serialization

### ISSUE THREAD

**Issue by punkkeks** [EasyRPG/liblcf#186]
When loading an "original" RPG project (created in RPG Maker 2k(3)) in Editor-Qt the generated XML (emu) files have `<Map id="0000">`. Because I don't know how the serialization works, I open an issue, instead of fixing it myself.

**Comment by Ghabry** [comment]
The problem here is simple: There is actually no ID, so the bug is here that the field is written.

**Comment by Ghabry** [comment]
Just to make this clear for anybody wondering about this: RPG_RT only cares about the Map ID in the filename (the numberic part in MapXXXX.lmu) there is ID field in the map file at all. The reason for this is probably that they avoid parsing all maps to get the stupid ID.
