### ISSUE TITLE
Incorrect lcf-size calculation for non-ascii-strings in event commands 

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/liblcf#196]
just a reminder for me, should be an easy fix.

Same as https://github.com/EasyRPG/Player/pull/1090 , but that code was Player specific to avoid reader_struct include.

To reproduce: Convert a LSD that contains umlauts with lcf2xml and back with xml2lcf. Load in RPG_RT: Stream read error.

Bug is in https://github.com/EasyRPG/liblcf/blob/465a0792784edbe0e351706aae5fda130cfad338/src/ldb_eventcommand.cpp#L44
or
https://github.com/EasyRPG/liblcf/blob/465a0792784edbe0e351706aae5fda130cfad338/src/ldb_eventcommand.cpp#L55

**Comment by carstene1ns** [comment]
I liked the former way better. We were not RPG_RT compatible, but did not crash on our own saves.
Thing is when we wait longer, we will get more and more negative feedback on google play and bug reports and such.
Maybe is better to revert 5abb593d2ec9 and merge #199 so we have more time to investigate.

**Comment by Ghabry** [comment]
I agree with your suggestion. I will create some faulty LSDs tomorrow to see if my PR works and then lgtm.

The "stream read error" bug must be somewhere else, just did really sloppy testing with my patch :/

**Comment by fmatthew5876** [comment]
Now that we have proven we can copy databases cleanly does this issue still exist?

**Comment by Ghabry** [comment]
event commands have there own event_commands_size field and the bug is in how the size of this field is calculated.
Is a bit hard to reproduce as it never happens always, maybe has nothign to do with the encoding at all.

To test it: Save a non-English game (it should have comments/messages with non-ascii chars in currently running events) with EasyRPG and try to load it in RPG_RT. A few give "stream read errors".
I can test a bit more if I can still reproduce this, maybe is really fixed.

**Comment by CherryDT** [comment]
Also make sure you test that with non-ASCII filenames in move event commands (play sound/change graphic). I had a bug with that in RMEventFactory because I forgot to test exactly that.

**Comment by Ghabry** [comment]
probably fixed by now?
