### ISSUE TITLE
Replace global Data::-writing of LDB_* and LMT_Reader with functions that return unique_ptr<RPG::Database> and unique_ptr<RPG::MapTree> (as already done for Savegames and Maps)

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/liblcf#207]
Imo it's bad style to operate on global data structures and this breaks some use cases e.g.:

- A tool that can compare two LDB/LMT files. 
- Multithreaded parsing of multiple LDB files in a GameBrowser
- Assuming the Android (or UWP) App GameBrowsers would use liblcf for game parsing some operations in the browser would be impossible while a game is running.
- Unrelated: Data:: is a really bad namespace name, e.g. UWP uses a Data::-namespace, too which causes compiler errors

Because this is backward incompatible and affects all our applications I propose the following deprecation steps:
1. Keep the Data:: fields (and store the last parsed LDB/LMT their), this is backward compatible
2. Modify all applications (Player, Editor, Tools) to use the new API
3. Delete the Data:: fields

**Comment by carstene1ns** [comment]
Addition to 1: [Mark `Data::` as `[[deprecated]]`](http://josephmansfield.uk/articles/marking-deprecated-c++14.html).
And because we do not use C++14, there is a [workaround for G++ and MSVC](https://stackoverflow.com/a/21265197).

**Comment by Ghabry** [comment]
At least for MSVC we could use [[deprecated]] directly because you cant set the C++ standard and according to MSDN VS2015 supports it but because this needs an ifdef we can try with the #pragma deprecated first if it works for fields.

**Comment by Ghabry** [comment]
Hm changing this is only backward compatible when Load(Xml) is used in a boolean context (bool becoms unique_ptr) which seems to be the case for Player +1

**Comment by fmatthew5876** [comment]
First step we could move `Data::` to player and remove the global from liblcf entirely. Then remaining work becomes a Player issue.

The roadblock here is some of the database pieces are used in the parsers for other structures, in particular for 2k3 version checks.

Once this dependency is broken somehow, fixing this would be easy.

**Comment by Ghabry** [comment]
imo the liblcf part is solved and this is more a Player problem (see linked issue)
