### ISSUE TITLE
Reader: Handle corrupted chunks better

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/liblcf#249]
Some games in #246 have corrupted chunks that liblcf can't handle. One example animation chunk from Devil and Angel is not 0 terminated, causing liblcf to continue reading past the end of the chunk and getting confused.

rm2k/3 is able to run these games, so it's a compatibility issue.

Make liblcf able to load these ldbs in the best way possible. More compatible with rm2k/3 the better. The games can be opened in the rm2k/3 editor to compare how liblcf interprets them vs how rm2k/3 does it.

Approach 1:

When returning from `ReadLcf()` calls, check how many bytes were read vs how many should have been read via `LcfSize()`. If the numbers don't match, seek back to the right position before going to the next chunk.

Approach 2:

Add a check before every read operation to ensure we never pass `LcfSize()`. This approach might be slower.

**Comment by Ghabry** [comment]
@fmatthew5876 As #250 is merged would you consider this resolved?

**Comment by fmatthew5876** [comment]
I guess so. We could further try to parse corrupted chunks exactly like RPG_RT does but I see little benefit to that.
