### ISSUE TITLE
Rename MapInfo::encounter_steps to MapInfo::encounter_rate

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/liblcf#265]
Leaving this one as a note to remember to do this later when we get the backlog of PR's merged in.

**Comment by Zegeri** [comment]
encounter_rate could mislead people into thinking that it's a ratio. For example, some people could understand encounter_rate = 10 as "10% chance of an encounter". encounter_steps leads to the correct interpretation, in my opinion.

**Comment by fmatthew5876** [comment]
I like encounter_steps, but then we need a different name for `SavePartyLocation::encounter_steps`. 

We have these:

1. `MapInfo::encounter_steps`
2. `SaveMapInfo::encounter_steps`
3. `Terrain::encounter_rate`
4. `SavePartyLocation::encounter_steps`

(1) and (2) need the same name. I think (3) is appropriate because it's really a multiplier. (4) needs to be differentiated from (1) and (2). It's the number of steps at run time as the encounter algorithm runs.

**Comment by fmatthew5876** [comment]
We also have `Game_Map::SetEncounterRate()` and `Game_Map::GetEncounterRate()`.

**Comment by Ghabry** [comment]
will add this one quickly before 0.8. Must have forgotten this one while adding the other chunks.
