### ISSUE TITLE
Do we still need iconv?

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/liblcf#274]
Right now we maintain icu and iconv code to do encoding conversions.

Are there still platforms that require us to continue supporting iconv?

**Comment by Ghabry** [comment]
We don't use iconv anymore in any of our official ports but there can be other ports not by us in the wild that use iconv.
iconv is usually easier to crosscompile, for ICU we needed a while (and lots of patches) to get this working everywhere.

The only feature we support with iconv is "recoding", everything else is ICU-only already (e.g. encoding auto detection).
