### ISSUE TITLE
liblcf should tag savegames with some version magic chunk

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/liblcf#299]
This way we can make sure to apply the right set of fixes for old savegames (walking in place bug post 0.5.4 comes to mind)
This field should be written in a way `RPG_RT` ignores it, but maybe not as a hack like https://github.com/EasyRPG/liblcf/issues/174#issuecomment-428997807.
Maybe should not be a real version, but more like a counter when there are changes to defaults.

**Comment by Ghabry** [comment]
works for me, only needs some chunk-number that won't conflict sooner or later with official stuff (we should agree on some common chunk-prefix here we use for any cutsom chunk). 0xEAS1 or sth but imo this number is a bit high but gives a style bonus ;)

**Comment by carstene1ns** [comment]
(fixed by #313, comment was missing)
