### ISSUE TITLE
Move lcf2xml over from Tools repo

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/liblcf#302]
`lcf2xml` is a generic tool that directly shows liblcf core capabilities.
IMO it should be part of liblcf (thinking of an example).

**Comment by Ghabry** [comment]
Makes sense to me so I'm in favor of this.

This would also solve the issue that we need a tool for regression/unit testing in the repo which can at least load and save LCF files as-is so you can binary-compare them for equality later.

**Comment by fmatthew5876** [comment]
+1 for this and other tools that are specific to lcf data. Especially for enabling tests.

**Comment by Ghabry** [comment]
Fixed by #369
