### ISSUE TITLE
SaveVehicleLocation::original_move_route_index??

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/liblcf#304]
We have this chunk 0x66 `SaveVehicleLocation::original_move_route_index`

Vehicles don't have custom move routes like map events.

What is the evidence that this chunk actually exists? It has the same chunk id as 0x66 `SaveMapEvent::original_move_route_index` so maybe this was somehow an accidental copy paste?

**Comment by Ghabry** [comment]
because this chunk isn't part of the inheritance of EventBase an error is possible.
