### ISSUE TITLE
Wrong event page variable condition when writing emu to lmu

### ISSUE THREAD

**Issue by elsemieni** [EasyRPG/liblcf#305]
RPG Maker version: 2003 1.12a
Lastest nightly liblcf in LCF2XML (Jan24 2019).

When you convert a map with a event that contains a tab with a variable condition from EMU to LMU (LMU to EMU is fine), the condition is changed.

Here's a test case:
We have this condition in a map.
![image](https://user-images.githubusercontent.com/1494687/51720352-040b2580-202c-11e9-905b-c4adc61a73f1.png)

Then after converting the map from LMU to EMU, and then back to LMU with LCF2XML, the condition changes to this one:
![image](https://user-images.githubusercontent.com/1494687/51720365-1a18e600-202c-11e9-996a-5427cf341166.png)

**Comment by carstene1ns** [comment]
Seems it is reset to default: [ref 1](https://github.com/EasyRPG/liblcf/blob/master/generator/csv/fields.csv#L639) → [ref 2](https://github.com/EasyRPG/liblcf/blob/master/generator/csv/enums.csv#L237).

**Comment by Ghabry** [comment]
hopefully this is really only for writing and not for reading, otherwise this needs a fix before 0.6
(though was not catched by my conversion test code)

**Comment by elsemieni** [comment]
Made a test case (RPG 2003 1.12a, LCF2XML from CI): 
[EventPage.zip](https://github.com/EasyRPG/liblcf/files/2799112/EventPage.zip)

Consists in two maps with the same content. Map0001, and Map0002.
Each one has a event with 6 pages, each of them with a different variable event page condition (each one of them).

Both maps are convertered to emu with LCF2XML.
Both emu output files have compared operator correctly defined, and Player (0.5.4 and last nightly, asuming that uses last version of liblcf) can read it correctly too. So I will discard reading issue I think.

Then, only Map0002 was converted back to lmu via the same tool. The result is that every variable condition in each page of the event in Map0002.lmu falls back to 1.

**Comment by elsemieni** [comment]
I think this is a regression. Now tested with October 2018 version of LCF2XML (I don't know wich version is exactly, but it's before emu format exists) and it generates the map correctly.

**Comment by Ghabry** [comment]
I just rendered a map programatically and encountered the same problem even without the XML roundtrip.

**Comment by Ghabry** [comment]
The problem is that for the 2k3 detection a LDB file must be loaded beacuse of our global variable mess.
#409 should help in fixing this.
