### ISSUE TITLE
Namespace and organize lcf headers

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/liblcf#342]
We need to reorganize the code before we can declare the liblcf API stable.

- [ ] Make all users `#include <liblcf/foo.H>` to avoid header conflicts.
- [ ] Put all `liblcf` code in an `lcf::` namespace.

**Comment by Ghabry** [comment]
- [ ] Get rid of everything in "Data::", global variables are ugly

**Comment by fmatthew5876** [comment]
As a first step, we could move `Data::` to player.

There are some parts of the liblcf parser that depends on grabbing stuff from `Data::`. That has to be refactored.

**Comment by fmatthew5876** [comment]
I'd like to propose we do this header file and namespace change sometime when we cut 6.2 release.

The main thing blocking me from doing it now is rebase hell. I wouldn't want to make a namespace PR here and in Player and have it stay for a long time and cause lots of rebase conflicts with other PRs.

Seems like right before a release when we have a rush to get everything in would be a good time to cut over.

**Comment by Ghabry** [comment]
moving this to 0.7.0 for now

**Comment by carstene1ns** [comment]
> Seems like right before a release when we have a rush to get everything in would be a good time to cut over.

*Yeah, because nobody makes mistakes when in a rush.* :roll_eyes: This is to be done right after a release, not before.

**Comment by fmatthew5876** [comment]
Ok sure, but maybe we could try to coordinate it, like right after the 6.2 release so it doesn't stay pending too long? This one is a rebase nightmare.
