### ISSUE TITLE
Rename some character lcf chunks

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/liblcf#378]
After this is merged: https://github.com/EasyRPG/Player/pull/2208

Rename these lcf chunks
* move_route.repeated -> done
* sprite_direction -> facing
* through vs route_through -> something?
* sprite_transparent -> sprite_hidden

**Comment by Ghabry** [comment]
should probably be adressed before 0.7 otherwise we break liblcf directly after again :D.

same for #265
