### ISSUE TITLE
Improve Expat target search

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/liblcf#385]
In the meanwhile (at least since 2.2.9 which is from Sep2019, maybe even older versions do this) the expat library is exporting a target ``expat::expat`` which replaces the ``FindEXPAT`` module. The Find module support should be dropped and only this target referenced instead.

This will break older expat versions but tbh this is an optional dependency on XML is more of a debugging tool.

The target name on Windows is wrong, this is fixed by 2.2.10 which is currently blocked by https://github.com/libexpat/libexpat/issues/415 on Windows.

So I consider this issue blocked until vcpkg updated to 2.2.10 when it is out.

**Comment by Ghabry** [comment]
A patch (not by me) landed in vcpkg which fixed the target. ``expat::expat`` should work now everywhere.

**Comment by hartwork** [comment]
> So I consider this issue blocked until vcpkg updated to 2.2.10 when it is out.

If that still holds, Expat 2.2.10 is out by now.

**Comment by Ghabry** [comment]
thanks for the info! I already started working on this at #397 . But is currently stuck on other CMake stuff I want to improve ^^'
