### ISSUE TITLE
Failed to ./configure

### ISSUE THREAD

**Issue by XadillaX** [EasyRPG/liblcf#429]
OS: Ubuntu 20.04

```
./configure: line 5183: syntax error near unexpected token `win32-dll'
./configure: line 5183: `LT_INIT(win32-dll)'
```

**Comment by fdelapena** [comment]
Hello, the `LT_INIT` macro requires having the `libtool` package. Is it installed?

**Comment by XadillaX** [comment]
Not yet. thx

**Comment by Ghabry** [comment]
@XadillaX  Please test if this fixes the problem for you and close the issue if yes, thanks!
