### ISSUE TITLE
Mixed Latin and Japanese breaks stuff

### ISSUE THREAD

**Issue by toaranotdev** [EasyRPG/liblcf#430]
- This does not happen with game assets but rather text like files (.txt, .po)
- Sometimes the encoding breaks, sometime it doesnt
- My text editor claims .po files generated by lcftrans' encoding is UTF-8, while RPGRewriters filelist.txt is somehow UTF-16BE, this is also the case with Vietnamese Nobihaza translation where lcftrans assume the encoding is UTF-16 somehow
- Happen also with full width latin like ＨＰ
- Possible cause: when characters are the equilvalent to others, say for example: ượ is equilvalent to p, when lcftrans read the games data, it prints out p because of the encoding, and when loaded in game, it doesnt treat the p as ượ but rather p, therefore the check for msgid and the original text ingame fails and fallback to the original language

**Comment by Ghabry** [comment]
We have never received any other complaints about encoding stuff concerning translations.

Except for Vietnamese which uses some hacked font stuff but this can be avoided now by using a proper TTF font.
