### ISSUE TITLE
lcf2xml - wrong encoding

### ISSUE THREAD

**Issue by SupSuper** [EasyRPG/liblcf#468]
When using the lcf2xml tool, the xml files are tagged with:
`<?xml version="1.0" encoding="UTF-8"?>`
However RPG Maker does not use UTF-8, and it's not being converted to UTF-8 either. This breaks any XML parser when there are foreign characters in the game. This is pretty easy to test by just putting áéíóú on a map name.

Either the tag should be corrected to match the RPG Maker encoding (probably the Windows default ISO-8859-1) or it should be converted.

**Comment by Ghabry** [comment]
This is solved by now. It uses the system encoding by default and accepts --encoding
