### ISSUE TITLE
autoconf install code path seems to be broken, not picked up by EasyRPG afterward

### ISSUE THREAD

**Issue by ell1e** [EasyRPG/liblcf#469]
The autoconf install code path in the latest dev version in the repository here seems to be broken, if liblcf is installed with these exact commands as found in the README it's not picked up by EasyRPG afterward:
```
./configure --prefix /usr  # find libraries, set options
make                       # compile the library
sudo make install          # install system-wide
```
This is what happens then when trying to run cmake for EasyRPG after doing that:
```
CMake Error at /usr/lib/cmake/liblcf/liblcf-config.cmake:19 (add_library):
  add_library cannot create ALIAS target "liblcf::liblcf" because target
  "PkgConfig::liblcf" is imported but not globally visible.
Call Stack (most recent call first):
  builds/cmake/Modules/PlayerFindPackage.cmake:54 (find_package)
  CMakeLists.txt:821 (player_find_package)
```
That problem doesn't occur when using the cmake build instructions from the README.

**Comment by Ghabry** [comment]
Can you tell me your CMake version? (``cmake --version``)

**Comment by Ghabry** [comment]
Closing because author did not respond.
